cmake_minimum_required(VERSION 3.15)
project(CusADi)

# Find CUDA package
include(CheckLanguage)
check_language(CUDA)
find_package(CUDAToolkit REQUIRED)
if(CMAKE_CUDA_COMPILER)
enable_language(CUDA)
include_directories(${CUDA_INCLUDE_DIRS})
message("CUDA found")
endif()
if(NOT DEFINED CMAKE_CUDA_ARCHITECTURES)
    set(CMAKE_CUDA_ARCHITECTURES 75 86)
endif()
message(${CMAKE_CUDA_ARCHITECTURES})

# Set C++ standard
set(CMAKE_CXX_STANDARD 11)

# Set CUDA flags
set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS}; -O3 -arch=sm_86 --use_fast_math)  # Adjust architecture as needed

set(DCMM_HUMANOID_FULL_SF_SOURCE codegen/dCMM_humanoid_full_sf.cu)
set(JACOBIAN_RIGHT_FOOT_HUMANOID_FULL_SF_SOURCE codegen/jacobian_right_foot_humanoid_full_sf.cu)
set(JACOBIAN_LEFT_FOOT_HUMANOID_FULL_SF_SOURCE codegen/jacobian_left_foot_humanoid_full_sf.cu)
set(BASE_POS_HUMANOID_FULL_SF_SOURCE codegen/base_pos_humanoid_full_sf.cu)
set(M_HUMANOID_FULL_SF_SOURCE codegen/M_humanoid_full_sf.cu)
set(C_HUMANOID_FULL_SF_SOURCE codegen/C_humanoid_full_sf.cu)
set(BASE_ROT_HUMANOID_FULL_SF_SOURCE codegen/base_rot_humanoid_full_sf.cu)
set(COM_HUMANOID_FULL_SF_SOURCE codegen/CoM_humanoid_full_sf.cu)
set(CM_HUMANOID_FULL_SF_SOURCE codegen/CM_humanoid_full_sf.cu)
set(CMM_HUMANOID_FULL_SF_SOURCE codegen/CMM_humanoid_full_sf.cu)
set(INERTIAL_QUANTITIES_SOURCE codegen/inertial_quantities.cu)
set(G_HUMANOID_FULL_SF_SOURCE codegen/G_humanoid_full_sf.cu)
set(DCM_HUMANOID_FULL_SF_SOURCE codegen/dCM_humanoid_full_sf.cu)

# Include directories for your header files
include_directories(${CMAKE_CURRENT_SOURCE_DIR})

add_library(dCMM_humanoid_full_sf SHARED ${DCMM_HUMANOID_FULL_SF_SOURCE})
target_link_libraries(dCMM_humanoid_full_sf)
add_library(jacobian_right_foot_humanoid_full_sf SHARED ${JACOBIAN_RIGHT_FOOT_HUMANOID_FULL_SF_SOURCE})
target_link_libraries(jacobian_right_foot_humanoid_full_sf)
add_library(jacobian_left_foot_humanoid_full_sf SHARED ${JACOBIAN_LEFT_FOOT_HUMANOID_FULL_SF_SOURCE})
target_link_libraries(jacobian_left_foot_humanoid_full_sf)
add_library(base_pos_humanoid_full_sf SHARED ${BASE_POS_HUMANOID_FULL_SF_SOURCE})
target_link_libraries(base_pos_humanoid_full_sf)
add_library(M_humanoid_full_sf SHARED ${M_HUMANOID_FULL_SF_SOURCE})
target_link_libraries(M_humanoid_full_sf)
add_library(C_humanoid_full_sf SHARED ${C_HUMANOID_FULL_SF_SOURCE})
target_link_libraries(C_humanoid_full_sf)
add_library(base_rot_humanoid_full_sf SHARED ${BASE_ROT_HUMANOID_FULL_SF_SOURCE})
target_link_libraries(base_rot_humanoid_full_sf)
add_library(CoM_humanoid_full_sf SHARED ${COM_HUMANOID_FULL_SF_SOURCE})
target_link_libraries(CoM_humanoid_full_sf)
add_library(CM_humanoid_full_sf SHARED ${CM_HUMANOID_FULL_SF_SOURCE})
target_link_libraries(CM_humanoid_full_sf)
add_library(CMM_humanoid_full_sf SHARED ${CMM_HUMANOID_FULL_SF_SOURCE})
target_link_libraries(CMM_humanoid_full_sf)
add_library(inertial_quantities SHARED ${INERTIAL_QUANTITIES_SOURCE})
target_link_libraries(inertial_quantities)
add_library(G_humanoid_full_sf SHARED ${G_HUMANOID_FULL_SF_SOURCE})
target_link_libraries(G_humanoid_full_sf)
add_library(dCM_humanoid_full_sf SHARED ${DCM_HUMANOID_FULL_SF_SOURCE})
target_link_libraries(dCM_humanoid_full_sf)
